/* ============
 * Mutation types for the app module
 * ============
 *
 * The mutation types that are available
 * on the app module.
 */

export const BOTTOM_NAV = 'BOTTOM_NAV';
export const CHART_TYPE = 'CHART_TYPE';
export const TRADE_PRICE = 'TRADE_PRICE';
export const TRADE_ACTION_INTENT = 'TRADE_ACTION_INTENT';
export const TRADE_PRICE_STATUS = 'TRADE_PRICE_STATUS';
export const TRADE_PRICE_STATUS_TM = 'TRADE_PRICE_STATUS_TM';
export const TRADE_FORM_VISIBLE = 'TRADE_FORM_VISIBLE';
export const TRADE_USER_ORDERS_VISIBLE = 'TRADE_USER_ORDERS_VISIBLE';
export const TRADE_PRICE_CHART_EXPANDED = 'TRADE_PRICE_CHART_EXPANDED';
export const TRADE_HISTORY_CALLBACK = 'TRADE_HISTORY_CALLBACK';
export const THEME_MODE_SWITCH = 'THEME_MODE_SWITCH';
export const THEME_MODE_SWITCH_DARK = 'THEME_MODE_SWITCH_DARK';
export const THEME_MODE_SWITCH_LIGHT = 'THEME_MODE_SWITCH_LIGHT';
export const THEME_ADD_BUSY_COMPONENT = 'THEME_ADD_BUSY_COMPONENT';
export const THEME_REMOVE_BUSY_COMPONENT = 'THEME_REMOVE_BUSY_COMPONENT';
export const READY = 'READY';
export const SET_APP_SETTING = 'SET_APP_SETTING';

export default {
  BOTTOM_NAV,
  CHART_TYPE,
  TRADE_PRICE,
  TRADE_ACTION_INTENT,
  TRADE_PRICE_STATUS,
  TRADE_PRICE_STATUS_TM,
  TRADE_FORM_VISIBLE,
  TRADE_USER_ORDERS_VISIBLE,
  TRADE_PRICE_CHART_EXPANDED,
  TRADE_HISTORY_CALLBACK,
  THEME_MODE_SWITCH,
  THEME_MODE_SWITCH_LIGHT,
  THEME_ADD_BUSY_COMPONENT,
  THEME_REMOVE_BUSY_COMPONENT,
  READY,
  SET_APP_SETTING,
};
