/* ============
 * Mutation types for the market module
 * ============
 *
 * The mutation types that are available
 * on the market module.
 */

export const TYPES = 'TYPES';
export const ACTIVE_TYPE = 'ACTIVE_TYPE';
export const ACTIVE_CURRENCY = 'ACTIVE_CURRENCY';
export const LIST = 'LIST';
export const DEFAULT_FAVORITE_PAIRS = 'DEFAULT_FAVORITE_PAIRS';
export const FAVORITE_PAIRS = 'FAVORITE_PAIRS';
export const FAVORITE_PAIRS_SUMMARIES = 'FAVORITE_PAIRS_SUMMARIES';
export const INFO = 'INFO';
export const TRADE_HISTORY = 'TRADE_HISTORY';
export const SETTINGS = 'SETTINGS';
export const SETTINGS_ALL = 'SETTINGS_ALL';
export const CURRENCIES = 'CURRENCIES';
export const CURRENCIES_ARR = 'CURRENCIES_ARR';
export const LOADING = 'LOADING';
export const LOADING_ARRAY = 'LOADING_ARRAY';
export const LOADING_LIST = 'LOADING_LIST';
export const LOADING_DEFAULT_FAVORITE_PAIRS = 'LOADING_DEFAULT_FAVORITE_PAIRS';
export const LOADING_FAVORITE_PAIRS = 'LOADING_FAVORITE_PAIRS';
export const LOADING_FAVORITE_PAIRS_SUMMARIES = 'LOADING_FAVORITE_PAIRS_SUMMARIES';
export const LOADING_HISTORY = 'LOADING_HISTORY';
export const TRADE_HISTORY_ADD = 'TRADE_HISTORY_ADD';
export const READY = 'READY';
export const EXCHANGE_RATE = 'EXCHANGE_RATE';
export const MARKETS = 'MARKETS';
export const ORDER_BOOK = 'ORDER_BOOK';
export const ORDER_BOOK_CHART = 'ORDER_BOOK_CHART';

export default {
  TYPES,
  ACTIVE_TYPE,
  ACTIVE_CURRENCY,
  LIST,
  DEFAULT_FAVORITE_PAIRS,
  FAVORITE_PAIRS,
  FAVORITE_PAIRS_SUMMARIES,
  INFO,
  TRADE_HISTORY,
  SETTINGS,
  SETTINGS_ALL,
  CURRENCIES,
  CURRENCIES_ARR,
  LOADING,
  LOADING_ARRAY,
  LOADING_LIST,
  LOADING_DEFAULT_FAVORITE_PAIRS,
  LOADING_FAVORITE_PAIRS,
  LOADING_FAVORITE_PAIRS_SUMMARIES,
  LOADING_HISTORY,
  TRADE_HISTORY_ADD,
  READY,
  EXCHANGE_RATE,
  MARKETS,
  ORDER_BOOK,
  ORDER_BOOK_CHART,
};
